# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml

[mgr]
show_hidden = true
ratio = [1, 1, 3]

sort_translit = true
linemode = "size"

scrolloff = 200
title_format = ""

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
]

[preview]
wrap = "yes"